spring.application.name=demoapp
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=health,info
management.info.env.enabled=true

info.app.name=demoapp
info.app.description=udemy-spring-hibernate-tutorial

app.user.name=Kirill
app.user.team=Java
